language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
virtualenv:
    system_site_packages: true
install:
    - pip install -r requirements.txt
script:
    - py.test --cov-report term-missing
after_success:
    - coveralls